# Generated by Django 3.2.7 on 2021-09-29 19:21

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, help_text='Введите цвет тега в HEX', max_length=18, null=True, unique=True, verbose_name='Цвет в HEX'),
        ),
    ]
